[book]
title = "ferroq 文档"
authors = ["yanzhi"]
language = "zh"
src = "src/zh"

[build]
build-dir = "book-zh"

[output.html]
git-repository-url = "https://github.com/yanzhi0922/ferroq"
edit-url-template = "https://github.com/yanzhi0922/ferroq/edit/main/docs/{path}"
no-section-label = false
additional-css = ["theme/custom.css"]
